### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [jcmedina/mytimes#4]
Overall met expectations.

HTML is well structured.  I didn't see any unneeded html or any major errors or flaws.

CSS is very efficient, the only issue being the body margin so there isn't an awkward gap with the header.

You commented both the html and css sections which is great, makes it easy to line up the html and css code.

The upcoming projects are going to be diving into media queries.

https://www.w3schools.com/css/css_rwd_mediaqueries.asp

See if you can use a media query to make this site fit into a mobile device screen size, bonus if you can make it look like an app.  This will help you the final stretch of projects.

**Comment by jcmedina** [comment]
Thank you so much for the feedback Farish! This is extremely helpful!
